### ISSUE TITLE
Test suite compilation failure with GHC 8.2

### ISSUE THREAD

**Issue by snoyberg** [adamgundry/units-parser#1]
```
[1 of 1] Compiling Text.Parse.Units ( Text/Parse/Units.hs, dist/build/Text/Parse/Units.o )
Preprocessing test suite 'main' for units-parser-0.1.0.0..
Building test suite 'main' for units-parser-0.1.0.0..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: Text.Parse.Units

<no location info>: error: 
Failing due to -Werror.
```

**Comment by goldfirere** [comment]
This doesn't seem worth it to cut another release. But I can't update the package on Hackage. @adamgundry, could you? And perhaps add me as a maintainer there, too. I'm RichardEisenberg. Thanks!

**Comment by adamgundry** [comment]
@goldfirere thanks for the fix. I've added you as a maintainer on Hackage.

Unfortunately we can't update the `other-modules` field without a new release, can we?

**Comment by goldfirere** [comment]
OK. I've uploaded it now, with a new version number.
